{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "from usgs import api\n",
    "from datetime import date"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "{'errorCode': None,\n",
       " 'error': '',\n",
       " 'data': '4909e7c311704646bb221b82330e5137',\n",
       " 'api_version': '1.4.0',\n",
       " 'access_level': 'user',\n",
       " 'catalog_id': 'default',\n",
       " 'executionTime': 0.52199983596802}"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "api.login('krodriguez','Otacon1105')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "{'errorCode': None,\n",
       " 'error': '',\n",
       " 'data': [{'fieldId': 20520,\n",
       "   'name': 'Landsat Product Identifier',\n",
       "   'fieldLink': 'https://lta.cr.usgs.gov/Landsat_8_C1.html#landsat_product_id',\n",
       "   'valueList': []},\n",
       "  {'fieldId': 20514,\n",
       "   'name': 'WRS Path',\n",
       "   'fieldLink': 'https://lta.cr.usgs.gov/Landsat_8_C1.html#wrs_path',\n",
       "   'valueList': []},\n",
       "  {'fieldId': 20516,\n",
       "   'name': 'WRS Row',\n",
       "   'fieldLink': 'https://lta.cr.usgs.gov/Landsat_8_C1.html#wrs_row',\n",
       "   'valueList': []},\n",
       "  {'fieldId': 20522,\n",
       "   'name': 'Land Cloud Cover',\n",
       "   'fieldLink': 'https://lta.cr.usgs.gov/Landsat_8_C1.html#land_cloud_cover',\n",
       "   'valueList': [{'value': None, 'name': 'All'},\n",
       "    {'value': '10', 'name': 'Less than 10%'},\n",
       "    {'value': '20', 'name': 'Less than 20%'},\n",
       "    {'value': '30', 'name': 'Less than 30%'},\n",
       "    {'value': '40', 'name': 'Less than 40%'},\n",
       "    {'value': '50', 'name': 'Less than 50%'},\n",
       "    {'value': '60', 'name': 'Less than 60%'},\n",
       "    {'value': '70', 'name': 'Less than 70%'},\n",
       "    {'value': '80', 'name': 'Less than 80%'},\n",
       "    {'value': '90', 'name': 'Less than 90%'},\n",
       "    {'value': '100', 'name': 'Less than 100%'}]},\n",
       "  {'fieldId': 20515,\n",
       "   'name': 'Scene Cloud Cover',\n",
       "   'fieldLink': 'https://lta.cr.usgs.gov/Landsat_8_C1.html#scene_cloud_cover',\n",
       "   'valueList': [{'value': None, 'name': 'All'},\n",
       "    {'value': '10', 'name': 'Less than 10%'},\n",
       "    {'value': '20', 'name': 'Less than 20%'},\n",
       "    {'value': '30', 'name': 'Less than 30%'},\n",
       "    {'value': '40', 'name': 'Less than 40%'},\n",
       "    {'value': '50', 'name': 'Less than 50%'},\n",
       "    {'value': '60', 'name': 'Less than 60%'},\n",
       "    {'value': '70', 'name': 'Less than 70%'},\n",
       "    {'value': '80', 'name': 'Less than 80%'},\n",
       "    {'value': '90', 'name': 'Less than 90%'},\n",
       "    {'value': '100', 'name': 'Less than 100%'}]},\n",
       "  {'fieldId': 20510,\n",
       "   'name': 'Collection Category',\n",
       "   'fieldLink': 'https://lta.cr.usgs.gov/Landsat_8_C1.html#collection_category',\n",
       "   'valueList': [{'value': None, 'name': 'All'},\n",
       "    {'value': 'T1', 'name': 'Tier 1'},\n",
       "    {'value': 'T2', 'name': 'Tier 2'},\n",
       "    {'value': 'RT', 'name': 'Real-Time'}]},\n",
       "  {'fieldId': 20517,\n",
       "   'name': 'Data Type Level-1',\n",
       "   'fieldLink': 'https://lta.cr.usgs.gov/Landsat_8_C1.html#data_type_l1',\n",
       "   'valueList': [{'value': None, 'name': 'All'},\n",
       "    {'value': 'L1TP', 'name': 'Level 1TP'},\n",
       "    {'value': 'L1GT', 'name': 'Level 1GT'},\n",
       "    {'value': 'L1GS', 'name': 'Level 1GS'}]},\n",
       "  {'fieldId': 20518,\n",
       "   'name': 'Sensor Identifier',\n",
       "   'fieldLink': 'https://lta.cr.usgs.gov/Landsat_8_C1.html#sensor_id        ',\n",
       "   'valueList': [{'value': None, 'name': 'All'},\n",
       "    {'value': 'OLI', 'name': 'OLI'},\n",
       "    {'value': 'OLI_TIRS', 'name': 'OLI_TIRS'},\n",
       "    {'value': 'TIRS', 'name': 'TIRS'}]},\n",
       "  {'fieldId': 20513,\n",
       "   'name': 'Day/Night Indicator',\n",
       "   'fieldLink': 'https://lta.cr.usgs.gov/Landsat_8_C1.html#day_or_night',\n",
       "   'valueList': [{'value': None, 'name': 'All'},\n",
       "    {'value': 'DAY', 'name': 'Day'},\n",
       "    {'value': 'NIGHT', 'name': 'Night'}]},\n",
       "  {'fieldId': 20511,\n",
       "   'name': 'Date L-1 Generated (Ex. YYYY/MM/DD)',\n",
       "   'fieldLink': 'https://lta.cr.usgs.gov/Landsat_8_C1.html#date_l1_generated',\n",
       "   'valueList': []},\n",
       "  {'fieldId': 20521,\n",
       "   'name': 'Geometric RMSE Model (meters)',\n",
       "   'fieldLink': 'https://lta.cr.usgs.gov/Landsat_8_C1.html#geometric_rmse_model',\n",
       "   'valueList': []},\n",
       "  {'fieldId': 20519,\n",
       "   'name': 'Nadir/Off Nadir',\n",
       "   'fieldLink': 'https://lta.cr.usgs.gov/Landsat_8_C1.html#nadir_offnadir',\n",
       "   'valueList': [{'value': None, 'name': 'All'},\n",
       "    {'value': 'NADIR', 'name': 'Nadir'},\n",
       "    {'value': 'OFFNADIR', 'name': 'Off Nadir'}]},\n",
       "  {'fieldId': 20512,\n",
       "   'name': 'Landsat Scene Identifier (Legacy)',\n",
       "   'fieldLink': 'https://lta.cr.usgs.gov/Landsat_8_C1.html#entity_id   ',\n",
       "   'valueList': []}],\n",
       " 'api_version': '1.4.0',\n",
       " 'access_level': 'user',\n",
       " 'catalog_id': 'EE',\n",
       " 'executionTime': 1.5149869918823}"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# get available metadata fields\n",
    "api.dataset_fields('LANDSAT_8_C1', 'EE')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "CPU times: user 185 ms, sys: 74.7 ms, total: 259 ms\n",
      "Wall time: 2.89 s\n"
     ]
    }
   ],
   "source": [
    "%%time\n",
    "start = date(year=2013, month=1, day=1)\n",
    "end = date(year=2017, month=1, day=1)\n",
    "\n",
    "# query for night time images around some Hawaiian Volcano\n",
    "roi_images = api.search('LANDSAT_8_C1', 'EE', lat=19.414405, lng=-155.272403, distance=300,\n",
    "           start_date='2013-04-01', end_date='2017-05-01', where={'20513':'Night'}, max_results=10)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "{'numberReturned': 10,\n",
       " 'totalHits': 18972,\n",
       " 'firstRecord': 1,\n",
       " 'lastRecord': 10,\n",
       " 'nextRecord': 11,\n",
       " 'results': [{'acquisitionDate': '2018-04-19',\n",
       "   'startTime': '2018-04-19',\n",
       "   'endTime': '2018-04-19',\n",
       "   'spatialFootprint': {'type': 'Polygon',\n",
       "    'coordinates': [[[-13.27912, 65.34584],\n",
       "      [-17.09272, 64.72402],\n",
       "      [-15.57424, 63.09646],\n",
       "      [-11.96088, 63.69161],\n",
       "      [-13.27912, 65.34584]]]},\n",
       "   'sceneBounds': '-17.09272,63.09646,-11.96088,65.34584',\n",
       "   'browseUrl': 'https://earthexplorer.usgs.gov/browse/landsat_8/2018/063/229/LC08_L1GT_063229_20180419_20180420_01_RT.jpg',\n",
       "   'dataAccessUrl': 'https://earthexplorer.usgs.gov/order/process?dataset_name=LANDSAT_8_C1&ordered=LC80632292018109LGN00&node=INVSVC',\n",
       "   'downloadUrl': 'https://earthexplorer.usgs.gov/download/external/options/LANDSAT_8_C1/LC80632292018109LGN00/INVSVC/',\n",
       "   'entityId': 'LC80632292018109LGN00',\n",
       "   'displayId': 'LC08_L1GT_063229_20180419_20180420_01_RT',\n",
       "   'metadataUrl': 'https://earthexplorer.usgs.gov/metadata/xml/12864/LC80632292018109LGN00/',\n",
       "   'fgdcMetadataUrl': 'https://earthexplorer.usgs.gov/fgdc/12864/LC80632292018109LGN00/save_xml',\n",
       "   'modifiedDate': '2018-04-19',\n",
       "   'orderUrl': 'https://earthexplorer.usgs.gov/order/process?dataset_name=LANDSAT_8_C1&ordered=LC80632292018109LGN00&node=INVSVC',\n",
       "   'bulkOrdered': False,\n",
       "   'ordered': False,\n",
       "   'summary': 'Entity ID: LC08_L1GT_063229_20180419_20180420_01_RT, Acquisition Date: 19-APR-18, Path: 63, Row: 229'},\n",
       "  {'acquisitionDate': '2018-04-19',\n",
       "   'startTime': '2018-04-19',\n",
       "   'endTime': '2018-04-19',\n",
       "   'spatialFootprint': {'type': 'Polygon',\n",
       "    'coordinates': [[[-14.49853, 66.71568],\n",
       "      [-18.48926, 66.06562],\n",
       "      [-16.82386, 64.45082],\n",
       "      [-13.05061, 65.07051],\n",
       "      [-14.49853, 66.71568]]]},\n",
       "   'sceneBounds': '-18.48926,64.45082,-13.05061,66.71568',\n",
       "   'browseUrl': 'https://earthexplorer.usgs.gov/browse/landsat_8/2018/063/230/LC08_L1GT_063230_20180419_20180420_01_RT.jpg',\n",
       "   'dataAccessUrl': 'https://earthexplorer.usgs.gov/order/process?dataset_name=LANDSAT_8_C1&ordered=LC80632302018109LGN00&node=INVSVC',\n",
       "   'downloadUrl': 'https://earthexplorer.usgs.gov/download/external/options/LANDSAT_8_C1/LC80632302018109LGN00/INVSVC/',\n",
       "   'entityId': 'LC80632302018109LGN00',\n",
       "   'displayId': 'LC08_L1GT_063230_20180419_20180420_01_RT',\n",
       "   'metadataUrl': 'https://earthexplorer.usgs.gov/metadata/xml/12864/LC80632302018109LGN00/',\n",
       "   'fgdcMetadataUrl': 'https://earthexplorer.usgs.gov/fgdc/12864/LC80632302018109LGN00/save_xml',\n",
       "   'modifiedDate': '2018-04-19',\n",
       "   'orderUrl': 'https://earthexplorer.usgs.gov/order/process?dataset_name=LANDSAT_8_C1&ordered=LC80632302018109LGN00&node=INVSVC',\n",
       "   'bulkOrdered': False,\n",
       "   'ordered': False,\n",
       "   'summary': 'Entity ID: LC08_L1GT_063230_20180419_20180420_01_RT, Acquisition Date: 19-APR-18, Path: 63, Row: 230'},\n",
       "  {'acquisitionDate': '2018-04-18',\n",
       "   'startTime': '2018-04-18',\n",
       "   'endTime': '2018-04-18',\n",
       "   'spatialFootprint': {'type': 'Polygon',\n",
       "    'coordinates': [[[-101.23995, 32.7951],\n",
       "      [-103.21957, 32.4121],\n",
       "      [-102.73875, 30.6868],\n",
       "      [-100.79671, 31.06973],\n",
       "      [-101.23995, 32.7951]]]},\n",
       "   'sceneBounds': '-103.21957,30.6868,-100.79671,32.7951',\n",
       "   'browseUrl': 'https://earthexplorer.usgs.gov/browse/landsat_8/2018/129/206/LC08_L1GT_129206_20180418_20180418_01_RT.jpg',\n",
       "   'dataAccessUrl': 'https://earthexplorer.usgs.gov/order/process?dataset_name=LANDSAT_8_C1&ordered=LC81292062018108LGN00&node=INVSVC',\n",
       "   'downloadUrl': 'https://earthexplorer.usgs.gov/download/external/options/LANDSAT_8_C1/LC81292062018108LGN00/INVSVC/',\n",
       "   'entityId': 'LC81292062018108LGN00',\n",
       "   'displayId': 'LC08_L1GT_129206_20180418_20180418_01_RT',\n",
       "   'metadataUrl': 'https://earthexplorer.usgs.gov/metadata/xml/12864/LC81292062018108LGN00/',\n",
       "   'fgdcMetadataUrl': 'https://earthexplorer.usgs.gov/fgdc/12864/LC81292062018108LGN00/save_xml',\n",
       "   'modifiedDate': '2018-04-18',\n",
       "   'orderUrl': 'https://earthexplorer.usgs.gov/order/process?dataset_name=LANDSAT_8_C1&ordered=LC81292062018108LGN00&node=INVSVC',\n",
       "   'bulkOrdered': False,\n",
       "   'ordered': False,\n",
       "   'summary': 'Entity ID: LC08_L1GT_129206_20180418_20180418_01_RT, Acquisition Date: 18-APR-18, Path: 129, Row: 206'},\n",
       "  {'acquisitionDate': '2018-04-17',\n",
       "   'startTime': '2018-04-17',\n",
       "   'endTime': '2018-04-17',\n",
       "   'spatialFootprint': {'type': 'Polygon',\n",
       "    'coordinates': [[[-16.37107, 65.346],\n",
       "      [-20.18442, 64.72416],\n",
       "      [-18.66571, 63.09661],\n",
       "      [-15.05258, 63.69178],\n",
       "      [-16.37107, 65.346]]]},\n",
       "   'sceneBounds': '-20.18442,63.09661,-15.05258,65.346',\n",
       "   'browseUrl': 'https://earthexplorer.usgs.gov/browse/landsat_8/2018/065/229/LC08_L1GT_065229_20180417_20180418_01_RT.jpg',\n",
       "   'dataAccessUrl': 'https://earthexplorer.usgs.gov/order/process?dataset_name=LANDSAT_8_C1&ordered=LC80652292018107LGN00&node=INVSVC',\n",
       "   'downloadUrl': 'https://earthexplorer.usgs.gov/download/external/options/LANDSAT_8_C1/LC80652292018107LGN00/INVSVC/',\n",
       "   'entityId': 'LC80652292018107LGN00',\n",
       "   'displayId': 'LC08_L1GT_065229_20180417_20180418_01_RT',\n",
       "   'metadataUrl': 'https://earthexplorer.usgs.gov/metadata/xml/12864/LC80652292018107LGN00/',\n",
       "   'fgdcMetadataUrl': 'https://earthexplorer.usgs.gov/fgdc/12864/LC80652292018107LGN00/save_xml',\n",
       "   'modifiedDate': '2018-04-17',\n",
       "   'orderUrl': 'https://earthexplorer.usgs.gov/order/process?dataset_name=LANDSAT_8_C1&ordered=LC80652292018107LGN00&node=INVSVC',\n",
       "   'bulkOrdered': False,\n",
       "   'ordered': False,\n",
       "   'summary': 'Entity ID: LC08_L1GT_065229_20180417_20180418_01_RT, Acquisition Date: 17-APR-18, Path: 65, Row: 229'},\n",
       "  {'acquisitionDate': '2018-04-17',\n",
       "   'startTime': '2018-04-17',\n",
       "   'endTime': '2018-04-17',\n",
       "   'spatialFootprint': {'type': 'Polygon',\n",
       "    'coordinates': [[[-17.59122, 66.71575],\n",
       "      [-21.58035, 66.06589],\n",
       "      [-19.91477, 64.45104],\n",
       "      [-16.14303, 65.07053],\n",
       "      [-17.59122, 66.71575]]]},\n",
       "   'sceneBounds': '-21.58035,64.45104,-16.14303,66.71575',\n",
       "   'browseUrl': 'https://earthexplorer.usgs.gov/browse/landsat_8/2018/065/230/LC08_L1GT_065230_20180417_20180418_01_RT.jpg',\n",
       "   'dataAccessUrl': 'https://earthexplorer.usgs.gov/order/process?dataset_name=LANDSAT_8_C1&ordered=LC80652302018107LGN00&node=INVSVC',\n",
       "   'downloadUrl': 'https://earthexplorer.usgs.gov/download/external/options/LANDSAT_8_C1/LC80652302018107LGN00/INVSVC/',\n",
       "   'entityId': 'LC80652302018107LGN00',\n",
       "   'displayId': 'LC08_L1GT_065230_20180417_20180418_01_RT',\n",
       "   'metadataUrl': 'https://earthexplorer.usgs.gov/metadata/xml/12864/LC80652302018107LGN00/',\n",
       "   'fgdcMetadataUrl': 'https://earthexplorer.usgs.gov/fgdc/12864/LC80652302018107LGN00/save_xml',\n",
       "   'modifiedDate': '2018-04-17',\n",
       "   'orderUrl': 'https://earthexplorer.usgs.gov/order/process?dataset_name=LANDSAT_8_C1&ordered=LC80652302018107LGN00&node=INVSVC',\n",
       "   'bulkOrdered': False,\n",
       "   'ordered': False,\n",
       "   'summary': 'Entity ID: LC08_L1GT_065230_20180417_20180418_01_RT, Acquisition Date: 17-APR-18, Path: 65, Row: 230'},\n",
       "  {'acquisitionDate': '2018-04-17',\n",
       "   'startTime': '2018-04-17',\n",
       "   'endTime': '2018-04-17',\n",
       "   'spatialFootprint': {'type': 'Polygon',\n",
       "    'coordinates': [[[-115.14482, 32.79546],\n",
       "      [-117.12573, 32.41221],\n",
       "      [-116.64484, 30.68694],\n",
       "      [-114.70154, 31.07013],\n",
       "      [-115.14482, 32.79546]]]},\n",
       "   'sceneBounds': '-117.12573,30.68694,-114.70154,32.79546',\n",
       "   'browseUrl': 'https://earthexplorer.usgs.gov/browse/landsat_8/2018/138/206/LC08_L1GT_138206_20180417_20180417_01_RT.jpg',\n",
       "   'dataAccessUrl': 'https://earthexplorer.usgs.gov/order/process?dataset_name=LANDSAT_8_C1&ordered=LC81382062018107LGN00&node=INVSVC',\n",
       "   'downloadUrl': 'https://earthexplorer.usgs.gov/download/external/options/LANDSAT_8_C1/LC81382062018107LGN00/INVSVC/',\n",
       "   'entityId': 'LC81382062018107LGN00',\n",
       "   'displayId': 'LC08_L1GT_138206_20180417_20180417_01_RT',\n",
       "   'metadataUrl': 'https://earthexplorer.usgs.gov/metadata/xml/12864/LC81382062018107LGN00/',\n",
       "   'fgdcMetadataUrl': 'https://earthexplorer.usgs.gov/fgdc/12864/LC81382062018107LGN00/save_xml',\n",
       "   'modifiedDate': '2018-04-17',\n",
       "   'orderUrl': 'https://earthexplorer.usgs.gov/order/process?dataset_name=LANDSAT_8_C1&ordered=LC81382062018107LGN00&node=INVSVC',\n",
       "   'bulkOrdered': False,\n",
       "   'ordered': False,\n",
       "   'summary': 'Entity ID: LC08_L1GT_138206_20180417_20180417_01_RT, Acquisition Date: 17-APR-18, Path: 138, Row: 206'},\n",
       "  {'acquisitionDate': '2018-04-17',\n",
       "   'startTime': '2018-04-17',\n",
       "   'endTime': '2018-04-17',\n",
       "   'spatialFootprint': {'type': 'Polygon',\n",
       "    'coordinates': [[[-115.52302, 34.23085],\n",
       "      [-117.53636, 33.84444],\n",
       "      [-117.04322, 32.12065],\n",
       "      [-115.07013, 32.5067],\n",
       "      [-115.52302, 34.23085]]]},\n",
       "   'sceneBounds': '-117.53636,32.12065,-115.07013,34.23085',\n",
       "   'browseUrl': 'https://earthexplorer.usgs.gov/browse/landsat_8/2018/138/207/LC08_L1GT_138207_20180417_20180417_01_RT.jpg',\n",
       "   'dataAccessUrl': 'https://earthexplorer.usgs.gov/order/process?dataset_name=LANDSAT_8_C1&ordered=LC81382072018107LGN00&node=INVSVC',\n",
       "   'downloadUrl': 'https://earthexplorer.usgs.gov/download/external/options/LANDSAT_8_C1/LC81382072018107LGN00/INVSVC/',\n",
       "   'entityId': 'LC81382072018107LGN00',\n",
       "   'displayId': 'LC08_L1GT_138207_20180417_20180417_01_RT',\n",
       "   'metadataUrl': 'https://earthexplorer.usgs.gov/metadata/xml/12864/LC81382072018107LGN00/',\n",
       "   'fgdcMetadataUrl': 'https://earthexplorer.usgs.gov/fgdc/12864/LC81382072018107LGN00/save_xml',\n",
       "   'modifiedDate': '2018-04-17',\n",
       "   'orderUrl': 'https://earthexplorer.usgs.gov/order/process?dataset_name=LANDSAT_8_C1&ordered=LC81382072018107LGN00&node=INVSVC',\n",
       "   'bulkOrdered': False,\n",
       "   'ordered': False,\n",
       "   'summary': 'Entity ID: LC08_L1GT_138207_20180417_20180417_01_RT, Acquisition Date: 17-APR-18, Path: 138, Row: 207'},\n",
       "  {'acquisitionDate': '2018-04-17',\n",
       "   'startTime': '2018-04-17',\n",
       "   'endTime': '2018-04-17',\n",
       "   'spatialFootprint': {'type': 'Polygon',\n",
       "    'coordinates': [[[-115.91039, 35.66526],\n",
       "      [-117.95807, 35.27546],\n",
       "      [-117.45151, 33.5532],\n",
       "      [-115.44689, 33.94229],\n",
       "      [-115.91039, 35.66526]]]},\n",
       "   'sceneBounds': '-117.95807,33.5532,-115.44689,35.66526',\n",
       "   'browseUrl': 'https://earthexplorer.usgs.gov/browse/landsat_8/2018/138/208/LC08_L1GT_138208_20180417_20180417_01_RT.jpg',\n",
       "   'dataAccessUrl': 'https://earthexplorer.usgs.gov/order/process?dataset_name=LANDSAT_8_C1&ordered=LC81382082018107LGN00&node=INVSVC',\n",
       "   'downloadUrl': 'https://earthexplorer.usgs.gov/download/external/options/LANDSAT_8_C1/LC81382082018107LGN00/INVSVC/',\n",
       "   'entityId': 'LC81382082018107LGN00',\n",
       "   'displayId': 'LC08_L1GT_138208_20180417_20180417_01_RT',\n",
       "   'metadataUrl': 'https://earthexplorer.usgs.gov/metadata/xml/12864/LC81382082018107LGN00/',\n",
       "   'fgdcMetadataUrl': 'https://earthexplorer.usgs.gov/fgdc/12864/LC81382082018107LGN00/save_xml',\n",
       "   'modifiedDate': '2018-04-17',\n",
       "   'orderUrl': 'https://earthexplorer.usgs.gov/order/process?dataset_name=LANDSAT_8_C1&ordered=LC81382082018107LGN00&node=INVSVC',\n",
       "   'bulkOrdered': False,\n",
       "   'ordered': False,\n",
       "   'summary': 'Entity ID: LC08_L1GT_138208_20180417_20180417_01_RT, Acquisition Date: 17-APR-18, Path: 138, Row: 208'},\n",
       "  {'acquisitionDate': '2018-04-16',\n",
       "   'startTime': '2018-04-16',\n",
       "   'endTime': '2018-04-16',\n",
       "   'spatialFootprint': {'type': 'Polygon',\n",
       "    'coordinates': [[[-77.82782, 25.60375],\n",
       "      [-79.67703, 25.23261],\n",
       "      [-79.2445, 23.50146],\n",
       "      [-77.42159, 23.87376],\n",
       "      [-77.82782, 25.60375]]]},\n",
       "   'sceneBounds': '-79.67703,23.50146,-77.42159,25.60375',\n",
       "   'browseUrl': 'https://earthexplorer.usgs.gov/browse/landsat_8/2018/115/201/LC08_L1GT_115201_20180416_20180416_01_RT.jpg',\n",
       "   'dataAccessUrl': 'https://earthexplorer.usgs.gov/order/process?dataset_name=LANDSAT_8_C1&ordered=LC81152012018106LGN00&node=INVSVC',\n",
       "   'downloadUrl': 'https://earthexplorer.usgs.gov/download/external/options/LANDSAT_8_C1/LC81152012018106LGN00/INVSVC/',\n",
       "   'entityId': 'LC81152012018106LGN00',\n",
       "   'displayId': 'LC08_L1GT_115201_20180416_20180416_01_RT',\n",
       "   'metadataUrl': 'https://earthexplorer.usgs.gov/metadata/xml/12864/LC81152012018106LGN00/',\n",
       "   'fgdcMetadataUrl': 'https://earthexplorer.usgs.gov/fgdc/12864/LC81152012018106LGN00/save_xml',\n",
       "   'modifiedDate': '2018-04-16',\n",
       "   'orderUrl': 'https://earthexplorer.usgs.gov/order/process?dataset_name=LANDSAT_8_C1&ordered=LC81152012018106LGN00&node=INVSVC',\n",
       "   'bulkOrdered': False,\n",
       "   'ordered': False,\n",
       "   'summary': 'Entity ID: LC08_L1GT_115201_20180416_20180416_01_RT, Acquisition Date: 16-APR-18, Path: 115, Row: 201'},\n",
       "  {'acquisitionDate': '2018-04-16',\n",
       "   'startTime': '2018-04-16',\n",
       "   'endTime': '2018-04-16',\n",
       "   'spatialFootprint': {'type': 'Polygon',\n",
       "    'coordinates': [[[-78.17189, 27.04363],\n",
       "      [-80.04393, 26.67044],\n",
       "      [-79.60323, 24.94035],\n",
       "      [-77.75953, 25.31449],\n",
       "      [-78.17189, 27.04363]]]},\n",
       "   'sceneBounds': '-80.04393,24.94035,-77.75953,27.04363',\n",
       "   'browseUrl': 'https://earthexplorer.usgs.gov/browse/landsat_8/2018/115/202/LC08_L1GT_115202_20180416_20180416_01_RT.jpg',\n",
       "   'dataAccessUrl': 'https://earthexplorer.usgs.gov/order/process?dataset_name=LANDSAT_8_C1&ordered=LC81152022018106LGN00&node=INVSVC',\n",
       "   'downloadUrl': 'https://earthexplorer.usgs.gov/download/external/options/LANDSAT_8_C1/LC81152022018106LGN00/INVSVC/',\n",
       "   'entityId': 'LC81152022018106LGN00',\n",
       "   'displayId': 'LC08_L1GT_115202_20180416_20180416_01_RT',\n",
       "   'metadataUrl': 'https://earthexplorer.usgs.gov/metadata/xml/12864/LC81152022018106LGN00/',\n",
       "   'fgdcMetadataUrl': 'https://earthexplorer.usgs.gov/fgdc/12864/LC81152022018106LGN00/save_xml',\n",
       "   'modifiedDate': '2018-04-16',\n",
       "   'orderUrl': 'https://earthexplorer.usgs.gov/order/process?dataset_name=LANDSAT_8_C1&ordered=LC81152022018106LGN00&node=INVSVC',\n",
       "   'bulkOrdered': False,\n",
       "   'ordered': False,\n",
       "   'summary': 'Entity ID: LC08_L1GT_115202_20180416_20180416_01_RT, Acquisition Date: 16-APR-18, Path: 115, Row: 202'}]}"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "roi_images['data']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "ename": "ConnectionError",
     "evalue": "('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mRemoteDisconnected\u001b[0m                        Traceback (most recent call last)",
      "\u001b[0;32m~/anaconda3/envs/numel/lib/python3.6/site-packages/urllib3-1.22-py3.6.egg/urllib3/connectionpool.py\u001b[0m in \u001b[0;36murlopen\u001b[0;34m(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)\u001b[0m\n\u001b[1;32m    600\u001b[0m                                                   \u001b[0mbody\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mbody\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mheaders\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mheaders\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 601\u001b[0;31m                                                   chunked=chunked)\n\u001b[0m\u001b[1;32m    602\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/numel/lib/python3.6/site-packages/urllib3-1.22-py3.6.egg/urllib3/connectionpool.py\u001b[0m in \u001b[0;36m_make_request\u001b[0;34m(self, conn, method, url, timeout, chunked, **httplib_request_kw)\u001b[0m\n\u001b[1;32m    386\u001b[0m                     \u001b[0;31m# otherwise it looks like a programming error was the cause.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 387\u001b[0;31m                     \u001b[0msix\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mraise_from\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0me\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    388\u001b[0m         \u001b[0;32mexcept\u001b[0m \u001b[0;34m(\u001b[0m\u001b[0mSocketTimeout\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mBaseSSLError\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mSocketError\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/numel/lib/python3.6/site-packages/urllib3-1.22-py3.6.egg/urllib3/packages/six.py\u001b[0m in \u001b[0;36mraise_from\u001b[0;34m(value, from_value)\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/numel/lib/python3.6/site-packages/urllib3-1.22-py3.6.egg/urllib3/connectionpool.py\u001b[0m in \u001b[0;36m_make_request\u001b[0;34m(self, conn, method, url, timeout, chunked, **httplib_request_kw)\u001b[0m\n\u001b[1;32m    382\u001b[0m                 \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 383\u001b[0;31m                     \u001b[0mhttplib_response\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mconn\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mgetresponse\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    384\u001b[0m                 \u001b[0;32mexcept\u001b[0m \u001b[0mException\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/numel/lib/python3.6/http/client.py\u001b[0m in \u001b[0;36mgetresponse\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   1330\u001b[0m             \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1331\u001b[0;31m                 \u001b[0mresponse\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mbegin\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1332\u001b[0m             \u001b[0;32mexcept\u001b[0m \u001b[0mConnectionError\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/numel/lib/python3.6/http/client.py\u001b[0m in \u001b[0;36mbegin\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    296\u001b[0m         \u001b[0;32mwhile\u001b[0m \u001b[0;32mTrue\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 297\u001b[0;31m             \u001b[0mversion\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mstatus\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mreason\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_read_status\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    298\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0mstatus\u001b[0m \u001b[0;34m!=\u001b[0m \u001b[0mCONTINUE\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/numel/lib/python3.6/http/client.py\u001b[0m in \u001b[0;36m_read_status\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    265\u001b[0m             \u001b[0;31m# sending a valid response.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 266\u001b[0;31m             raise RemoteDisconnected(\"Remote end closed connection without\"\n\u001b[0m\u001b[1;32m    267\u001b[0m                                      \" response\")\n",
      "\u001b[0;31mRemoteDisconnected\u001b[0m: Remote end closed connection without response",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mProtocolError\u001b[0m                             Traceback (most recent call last)",
      "\u001b[0;32m~/anaconda3/envs/numel/lib/python3.6/site-packages/requests-2.18.4-py3.6.egg/requests/adapters.py\u001b[0m in \u001b[0;36msend\u001b[0;34m(self, request, stream, timeout, verify, cert, proxies)\u001b[0m\n\u001b[1;32m    439\u001b[0m                     \u001b[0mretries\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mmax_retries\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 440\u001b[0;31m                     \u001b[0mtimeout\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mtimeout\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    441\u001b[0m                 )\n",
      "\u001b[0;32m~/anaconda3/envs/numel/lib/python3.6/site-packages/urllib3-1.22-py3.6.egg/urllib3/connectionpool.py\u001b[0m in \u001b[0;36murlopen\u001b[0;34m(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)\u001b[0m\n\u001b[1;32m    638\u001b[0m             retries = retries.increment(method, url, error=e, _pool=self,\n\u001b[0;32m--> 639\u001b[0;31m                                         _stacktrace=sys.exc_info()[2])\n\u001b[0m\u001b[1;32m    640\u001b[0m             \u001b[0mretries\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msleep\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/numel/lib/python3.6/site-packages/urllib3-1.22-py3.6.egg/urllib3/util/retry.py\u001b[0m in \u001b[0;36mincrement\u001b[0;34m(self, method, url, response, error, _pool, _stacktrace)\u001b[0m\n\u001b[1;32m    356\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0mread\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mFalse\u001b[0m \u001b[0;32mor\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_is_method_retryable\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mmethod\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 357\u001b[0;31m                 \u001b[0;32mraise\u001b[0m \u001b[0msix\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mreraise\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mtype\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0merror\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0merror\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0m_stacktrace\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    358\u001b[0m             \u001b[0;32melif\u001b[0m \u001b[0mread\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/numel/lib/python3.6/site-packages/urllib3-1.22-py3.6.egg/urllib3/packages/six.py\u001b[0m in \u001b[0;36mreraise\u001b[0;34m(tp, value, tb)\u001b[0m\n\u001b[1;32m    684\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mvalue\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m__traceback__\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0mtb\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 685\u001b[0;31m             \u001b[0;32mraise\u001b[0m \u001b[0mvalue\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwith_traceback\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mtb\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    686\u001b[0m         \u001b[0;32mraise\u001b[0m \u001b[0mvalue\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/numel/lib/python3.6/site-packages/urllib3-1.22-py3.6.egg/urllib3/connectionpool.py\u001b[0m in \u001b[0;36murlopen\u001b[0;34m(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)\u001b[0m\n\u001b[1;32m    600\u001b[0m                                                   \u001b[0mbody\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mbody\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mheaders\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mheaders\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 601\u001b[0;31m                                                   chunked=chunked)\n\u001b[0m\u001b[1;32m    602\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/numel/lib/python3.6/site-packages/urllib3-1.22-py3.6.egg/urllib3/connectionpool.py\u001b[0m in \u001b[0;36m_make_request\u001b[0;34m(self, conn, method, url, timeout, chunked, **httplib_request_kw)\u001b[0m\n\u001b[1;32m    386\u001b[0m                     \u001b[0;31m# otherwise it looks like a programming error was the cause.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 387\u001b[0;31m                     \u001b[0msix\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mraise_from\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0me\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    388\u001b[0m         \u001b[0;32mexcept\u001b[0m \u001b[0;34m(\u001b[0m\u001b[0mSocketTimeout\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mBaseSSLError\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mSocketError\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/numel/lib/python3.6/site-packages/urllib3-1.22-py3.6.egg/urllib3/packages/six.py\u001b[0m in \u001b[0;36mraise_from\u001b[0;34m(value, from_value)\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/numel/lib/python3.6/site-packages/urllib3-1.22-py3.6.egg/urllib3/connectionpool.py\u001b[0m in \u001b[0;36m_make_request\u001b[0;34m(self, conn, method, url, timeout, chunked, **httplib_request_kw)\u001b[0m\n\u001b[1;32m    382\u001b[0m                 \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 383\u001b[0;31m                     \u001b[0mhttplib_response\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mconn\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mgetresponse\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    384\u001b[0m                 \u001b[0;32mexcept\u001b[0m \u001b[0mException\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/numel/lib/python3.6/http/client.py\u001b[0m in \u001b[0;36mgetresponse\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   1330\u001b[0m             \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1331\u001b[0;31m                 \u001b[0mresponse\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mbegin\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1332\u001b[0m             \u001b[0;32mexcept\u001b[0m \u001b[0mConnectionError\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/numel/lib/python3.6/http/client.py\u001b[0m in \u001b[0;36mbegin\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    296\u001b[0m         \u001b[0;32mwhile\u001b[0m \u001b[0;32mTrue\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 297\u001b[0;31m             \u001b[0mversion\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mstatus\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mreason\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_read_status\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    298\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0mstatus\u001b[0m \u001b[0;34m!=\u001b[0m \u001b[0mCONTINUE\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/numel/lib/python3.6/http/client.py\u001b[0m in \u001b[0;36m_read_status\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    265\u001b[0m             \u001b[0;31m# sending a valid response.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 266\u001b[0;31m             raise RemoteDisconnected(\"Remote end closed connection without\"\n\u001b[0m\u001b[1;32m    267\u001b[0m                                      \" response\")\n",
      "\u001b[0;31mProtocolError\u001b[0m: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mConnectionError\u001b[0m                           Traceback (most recent call last)",
      "\u001b[0;32m<timed exec>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n",
      "\u001b[0;32m~/repos/usgs/usgs/api.py\u001b[0m in \u001b[0;36msearch\u001b[0;34m(dataset, node, lat, lng, distance, ll, ur, start_date, end_date, where, max_results, starting_number, sort_order, extended, api_key)\u001b[0m\n\u001b[1;32m    309\u001b[0m         \u001b[0mapi_key\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mapi_key\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    310\u001b[0m     )}\n\u001b[0;32m--> 311\u001b[0;31m     \u001b[0mr\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mrequests\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mpost\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0murl\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mpayload\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    312\u001b[0m     \u001b[0mresponse\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mr\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mjson\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    313\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/numel/lib/python3.6/site-packages/requests-2.18.4-py3.6.egg/requests/api.py\u001b[0m in \u001b[0;36mpost\u001b[0;34m(url, data, json, **kwargs)\u001b[0m\n\u001b[1;32m    110\u001b[0m     \"\"\"\n\u001b[1;32m    111\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 112\u001b[0;31m     \u001b[0;32mreturn\u001b[0m \u001b[0mrequest\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'post'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0murl\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mdata\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mdata\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mjson\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mjson\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    113\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    114\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/numel/lib/python3.6/site-packages/requests-2.18.4-py3.6.egg/requests/api.py\u001b[0m in \u001b[0;36mrequest\u001b[0;34m(method, url, **kwargs)\u001b[0m\n\u001b[1;32m     56\u001b[0m     \u001b[0;31m# cases, and look like a memory leak in others.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     57\u001b[0m     \u001b[0;32mwith\u001b[0m \u001b[0msessions\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mSession\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0msession\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 58\u001b[0;31m         \u001b[0;32mreturn\u001b[0m \u001b[0msession\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mrequest\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mmethod\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mmethod\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0murl\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0murl\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     59\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     60\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/numel/lib/python3.6/site-packages/requests-2.18.4-py3.6.egg/requests/sessions.py\u001b[0m in \u001b[0;36mrequest\u001b[0;34m(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)\u001b[0m\n\u001b[1;32m    506\u001b[0m         }\n\u001b[1;32m    507\u001b[0m         \u001b[0msend_kwargs\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mupdate\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0msettings\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 508\u001b[0;31m         \u001b[0mresp\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msend\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mprep\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0msend_kwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    509\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    510\u001b[0m         \u001b[0;32mreturn\u001b[0m \u001b[0mresp\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/numel/lib/python3.6/site-packages/requests-2.18.4-py3.6.egg/requests/sessions.py\u001b[0m in \u001b[0;36msend\u001b[0;34m(self, request, **kwargs)\u001b[0m\n\u001b[1;32m    616\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    617\u001b[0m         \u001b[0;31m# Send the request\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 618\u001b[0;31m         \u001b[0mr\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0madapter\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msend\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mrequest\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    619\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    620\u001b[0m         \u001b[0;31m# Total elapsed time of the request (approximately)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/numel/lib/python3.6/site-packages/requests-2.18.4-py3.6.egg/requests/adapters.py\u001b[0m in \u001b[0;36msend\u001b[0;34m(self, request, stream, timeout, verify, cert, proxies)\u001b[0m\n\u001b[1;32m    488\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    489\u001b[0m         \u001b[0;32mexcept\u001b[0m \u001b[0;34m(\u001b[0m\u001b[0mProtocolError\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0msocket\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0merror\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0merr\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 490\u001b[0;31m             \u001b[0;32mraise\u001b[0m \u001b[0mConnectionError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0merr\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mrequest\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mrequest\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    491\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    492\u001b[0m         \u001b[0;32mexcept\u001b[0m \u001b[0mMaxRetryError\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mConnectionError\u001b[0m: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))"
     ]
    }
   ],
   "source": [
    "%%time\n",
    "all_roi_images = api.search('LANDSAT_8_C1', 'EE', lat=19.414405, lng=-155.272403,\n",
    "           start_date='2013-04-01', end_date='2017-05-01', where={'20513':'Night'})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'all_roi_images' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-9-d535f9cc35ba>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mall_roi_images\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m'data'\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m'numberReturned'\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;31mNameError\u001b[0m: name 'all_roi_images' is not defined"
     ]
    }
   ],
   "source": [
    "all_roi_images['data']['numberReturned']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "ename": "SyntaxError",
     "evalue": "invalid syntax (<ipython-input-10-1480bbf44847>, line 2)",
     "output_type": "error",
     "traceback": [
      "\u001b[0;36m  File \u001b[0;32m\"<ipython-input-10-1480bbf44847>\"\u001b[0;36m, line \u001b[0;32m2\u001b[0m\n\u001b[0;31m    api.download('LANDSAT_8_C1', 'EE', product'LC81661972016362LGN01')\u001b[0m\n\u001b[0m                                                                    ^\u001b[0m\n\u001b[0;31mSyntaxError\u001b[0m\u001b[0;31m:\u001b[0m invalid syntax\n"
     ]
    }
   ],
   "source": [
    "import usgs\n",
    "api.download('LANDSAT_8_C1', 'EE', product'LC81661972016362LGN01')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
